#!/bin/bash

# Credits: http://blog.ittybittyapps.com/blog/2013/09/03/git-pre-push/

(cd elm && elm-make src/Main.elm --output=../assets/gen/javascripts/elm-main.js --yes)
RESULT=$?
if [ $RESULT -ne 0 ]; then
    echo "failed to compile Main.elm"
    exit 1
fi

git add assets/gen/javascripts/elm-main.js

exit 0