#!/bin/bash

# Credits: http://blog.ittybittyapps.com/blog/2013/09/03/git-pre-push/

(cd elm && elm-make Main.elm --output=../assets/gen/javascripts/elm-main.js)
RESULT=$?
if [ $RESULT -ne 0 ]; then
    echo "failed $CMD"
    exit 1
fi

exit 0